### ISSUE TITLE
Click-To-Whisper has no functionality

### ISSUE THREAD

**Issue by KevinTyrrell** [GoldpawsStuff/BigInputBox#8]
If the user attempts to
* Click on a user's name in chat
* Right click any player's frame, selecting the 'whisper' option
* Right click on any player's name the *Who*, *Guild*, or *Friends* pane, and select the 'Whisper' option

the BigInputBox does not display.

Expected: BigInputBox should display in the above situations, mirroring what the chat pane does.

Note: This may not be possible due to in-game restrictions -- not an expert on that area of the WoW API.

**Comment by Goldpaw** [comment]
Can't replicate this, as it would include putting text into the input box. The `/charactername` text. When an addon edits the contents of the editbox, the editbox becomes tainted and can no longer cast secure commands, like `/cast` or other character functions through chat. 

The only way to maintain the secure status of the editbox is to never edit any text, and only be opened as a direct result of a keybind. Attaching the box to clicking names in the regular chat frames would require us to both manually open the editbox, and manually edit the text in the box. 

It's intentional that the box does not replicate this. It's a result of blizzard limitations.
